let scriptList = [
  "../script/model/confirm.js",
  "../script/Toast/toast.js",
  "../script/bus/constants.js",
  "../src/arithmetics/arithmetics.js",
  "../script/color.js",
  "../script/colorIf.js",
  "../script/navBar/navbar.js",
  "../script/memory/memory.js",
  "../script/memory/slider.js",
  "../script/memory/hover.js",
  "../script/memory/edit.js",
  "../script/memory/toggle.js",
  "../script/memory/operation/memoryColors.js",
  "../script/memory/operation/memory.js",
  "../script/bus/AR/ARColors.js",
  "../script/bus/AR/AR.js",
  "../script/bus/PC/PCColors.js",
  "../script/bus/PC/PC.js",
  "../script/bus/DR/DRColors.js",
  "../script/bus/DR/DR.js",
  "../script/bus/B/BColors.js",
  "../script/bus/B/B.js",
  "../script/bus/AC/ACColors.js",
  "../script/bus/AC/AC.js",
  "../script/bus/TR/TRColors.js",
  "../script/bus/TR/TR.js",
  "../script/bus/IR/IRColors.js",
  "../script/bus/IR/IR.js",
  "../script/bus/OUTR/OUTRColors.js",
  "../script/bus/OUTR/OUTR.js",
  "../script/bus/INPR/INPRColors.js",
  "../script/bus/INPR/INPR.js",
  "../script/bus/ALU/ALUColors.js",
  "../script/bus/ALU/ALU.js",
  "../script/bus/FlipFlop/FF.js",
  "../script/bus/SC/SC.js",
  "../script/bus/SC/SCColors.js",
  "../script/codeEditor/model.js",
  "../src/decoder/decoder.js",
  "../src/registers/sequenceCounter.js",
  "../src/operations/decodeOperations.js",
  "../src/operations/fetchOperations.js",
  "../src/operations/mriOperations.js",
  "../src/operations/rriOperations.js",
  "../src/operations/resolveEffectiveAddressOperations.js",
  "../src/instructions/instructions.js",
  "../src/ds/stack.js",
  "../src/componentInstances.js",
  "../src/assembler/scanner.js",
  "../src/assembler/assembler.js",
  "../src/assembler/run.js",
  "../script/pausePlay/PP.js",
  "../script/video/video.js",
];

scriptList.forEach(function (s) {
  let script = document.createElement("script"); //creating <script> element
  script.src = s;
  script.async = false;
  document.body.appendChild(script);
});
